spring:
  application:
    name: aicareerplatform

  datasource:
    url: jdbc:postgresql://localhost:5433/aicareerplatform
    username: postgres
    password: root

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ai:
    # =========================
    # GEMINI
    # =========================
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            options:
              model: gemini-embedding-001
              dimensions: 1536

    # =========================
    # PGVECTOR
    # =========================
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 1536
        index-type: HNSW
        distance-type: COSINE_DISTANCE

    # =========================
    # GROQ - OpenAI Compatible
    # =========================
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai/v1
      chat:
        options:
          model: openai/gpt-oss-120b

# =========================
# JWT
# =========================
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

# =========================
# AI PROVIDER
# =========================
ai-provider:
  active: gemini